// build — publish the corpus and the compiled tool layer as static assets.
//
// This is the `sitemap.xml` half of the analogy: a deployed app tells machine
// readers what it is (`/.well-known/sightmap.json`) and what it can do
// (`/.well-known/sightkick.json`), served from the CDN like any other public
// file. The runtime that turns the IR into WebMCP tools ships alongside, and
// `webmcp.init.js` bundles runtime + IR into the one file agent-browser's
// `--init-script` wants — the artifact its `webmcp-gen` skill would otherwise
// hand-write.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { parseArgs } from "./args.mjs";
import { requireBin, run } from "./cli-tools.mjs";

export const WELL_KNOWN = {
  corpus: ".well-known/sightmap.json",
  ir: ".well-known/sightkick.json",
  runtime: "sightkick-runtime.js",
};

/** runtime bundle + IR → a single self-booting script for `agent-browser --init-script`. */
export function renderInitScript(runtimeJs, irJson) {
  const ir = JSON.stringify(JSON.parse(irJson));
  return (
    `// Generated by sightmap-next build — do not edit. Sightkick runtime + compiled IR.\n` +
    `// Load before navigation:  agent-browser --init-script ./webmcp.init.js open <url>\n` +
    `// Then:                    agent-browser webmcp list\n` +
    `window.__sightkick_ir = ${ir};\n` +
    runtimeJs +
    `\n;(function(){ if (window.__sightkick && !window.__sightkick.ir) window.__sightkick.load(window.__sightkick_ir); })();\n`
  );
}

export function build(
  root,
  {
    publicDir = "public",
    initScript = "webmcp.init.js",
    sightkickArgs = [],
    log = console.log,
  } = {},
) {
  const sightmap = requireBin("sightmap", root, "npm i -D @sightmap/sightmap");
  const sightkick = requireBin(
    "sightkick",
    root,
    "npm i -D @sightmap/sightkick",
  );
  const pub = join(root, publicDir);
  mkdirSync(join(pub, ".well-known"), { recursive: true });

  const corpusOut = join(pub, WELL_KNOWN.corpus);
  run(sightmap, ["export", root, "-o", corpusOut], { cwd: root });
  log(`✓ ${relative(root, corpusOut)}  (sightmap export)`);

  const irOut = join(pub, WELL_KNOWN.ir);
  const b = run(sightkick, ["build", root, "-o", irOut, ...sightkickArgs], {
    cwd: root,
  });
  log(
    `✓ ${relative(root, irOut)}  (${(b.stdout || b.stderr).trim().split("\n").pop()})`,
  );

  const rtOut = join(pub, WELL_KNOWN.runtime);
  run(sightkick, ["runtime", "-o", rtOut], { cwd: root });
  log(`✓ ${relative(root, rtOut)}  (sightkick runtime)`);

  if (initScript) {
    const out = join(root, initScript);
    writeFileSync(
      out,
      renderInitScript(
        readFileSync(rtOut, "utf8"),
        readFileSync(irOut, "utf8"),
      ),
    );
    log(
      `✓ ${relative(root, out)}  (runtime + IR, for agent-browser --init-script)`,
    );
  }
  return { corpusOut, irOut, rtOut };
}

export async function buildCommand(argv) {
  const args = parseArgs(argv, { booleans: ["init-script"] });
  const root = args._[0] ?? process.cwd();
  build(root, {
    publicDir: args["public-dir"],
    initScript:
      args["init-script"] === false
        ? null
        : typeof args["init-script"] === "string"
          ? args["init-script"]
          : undefined,
    sightkickArgs: args["sightkick-args"]
      ? String(args["sightkick-args"]).split(/\s+/).filter(Boolean)
      : [],
  });
  return 0;
}
